# Generated by Django 5.0.2 on 2025-06-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Калорийность (ккал)'),
        ),
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Углеводы (г)'),
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Жиры (г)'),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Белки (г)'),
        ),
    ]
