# Generated by Django 5.0.2 on 2025-06-02 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_product_calories_product_carbs_product_fats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('delivery_type', models.CharField(choices=[('pickup_10a', 'Самовывоз с Лобачевского 10а'), ('pickup_43', 'Самовывоз с Щапова 43'), ('pickup_51', 'Самовывоз с Сибгата Хакима 51 (ЖК Столичный)'), ('pickup_20a', 'Самовывоз с Чистопольской 20а'), ('delivery', 'Доставка')], max_length=32, verbose_name='Способ получения')),
                ('need_cutlery', models.BooleanField(default=True, verbose_name='Одноразовые приборы')),
                ('need_call', models.BooleanField(default=True, verbose_name='Звонок для подтверждения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('time', models.CharField(blank=True, max_length=20, verbose_name='Время к заказу')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('items_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость товаров')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafe.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafe.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
