# Generated by Django 5.0.2 on 2025-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_text',
            field=models.TextField(blank=True, verbose_name='Чек (текст)'),
        ),
    ]
