# Generated by Django 5.2.1 on 2026-04-20 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_order_receipt_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        (
                            'ALTER TABLE cafe_order '
                            'ADD COLUMN IF NOT EXISTS user_id integer NULL'
                        ),
                        (
                            'CREATE INDEX IF NOT EXISTS cafe_order_user_id_f0b31dd9 '
                            'ON cafe_order (user_id)'
                        ),
                        (
                            "DO $$ BEGIN "
                            "IF NOT EXISTS ("
                            "SELECT 1 FROM pg_constraint "
                            "WHERE conname = 'cafe_order_user_id_f0b31dd9_fk_auth_user_id'"
                            ") THEN "
                            "ALTER TABLE cafe_order "
                            "ADD CONSTRAINT cafe_order_user_id_f0b31dd9_fk_auth_user_id "
                            "FOREIGN KEY (user_id) REFERENCES auth_user(id) "
                            "DEFERRABLE INITIALLY DEFERRED; "
                            "END IF; "
                            "END $$;"
                        ),
                    ],
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='user',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('default_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес по умолчанию')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
