# Generated by Django 5.2.1 on 2026-04-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='cafe.product', verbose_name='Любимые товары'),
        ),
    ]
